
CREATE TABLE `gd_integral_sub_detail` (
  `pk_integral_sub_detail` VARCHAR(30) NOT NULL COMMENT '主键',
  `customer_idcard` VARCHAR(19) NOT NULL COMMENT '客户身份证号',
  `customer_integral` DOUBLE DEFAULT NULL COMMENT '客户积分',
  `customer_account` VARCHAR(30) DEFAULT NULL COMMENT '客户账号',
  `deposit_receipt_num` VARCHAR(30) DEFAULT NULL COMMENT '存单号',
  `deposit_receipt_amt` DOUBLE DEFAULT NULL COMMENT '存单金额',
  `conversion_detail` VARCHAR(128) DEFAULT NULL COMMENT '兑换明细',
  `input_date` VARCHAR(10) DEFAULT NULL COMMENT '录入时间',
  `option_org` VARCHAR(20) DEFAULT NULL COMMENT '操作机构',
  `dr` CHAR(1) DEFAULT NULL COMMENT '删除标志',
  `def2` VARCHAR(50) DEFAULT NULL COMMENT '积分单位',
  `def3` VARCHAR(50) DEFAULT NULL COMMENT '年份',
  `def4` CHAR(1) DEFAULT NULL COMMENT '类型：1，2，3，4',
  `ts` CHAR(19) DEFAULT NULL,
  `def1` VARCHAR(50) DEFAULT NULL COMMENT '类型：中文',
  `create_user` VARCHAR(20) DEFAULT NULL,
  `create_user_org` VARCHAR(20) DEFAULT NULL,
  `createtime` CHAR(19) DEFAULT NULL,
  `modifiedtime` CHAR(19) DEFAULT NULL,
  `modifier` VARCHAR(20) DEFAULT NULL,
  `def5` VARCHAR(50) DEFAULT NULL COMMENT '积分兑换的数量',
  `def6` VARCHAR(50) DEFAULT NULL COMMENT '资金来源',
  `def7` VARCHAR(50) DEFAULT NULL COMMENT '销售人',
  `def8` VARCHAR(50) DEFAULT NULL COMMENT '积分兑换批次号',
  `def9` VARCHAR(50) DEFAULT NULL,
  `def10` VARCHAR(50) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;